version: '3'
services:
  db:
    container_name: db
    image: postgres:15-alpine
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - .env

  backend:
    container_name: backend
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - media_value:/app/media/
      - static_value:/backend_static/
    depends_on:
      - db

  nginx:
    container_name: nginx
    restart: always
    build:
      context: .
      dockerfile: nginx/Dockerfile
    ports:
      - "8000:80"
    volumes:
      - media_value:/var/html/media/
      - static_value:/staticfiles/
      
    depends_on:
      - backend

volumes:
  media_value:
  static_value: