# Generated by Django 4.2.10 on 2024-03-03 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Merch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated",
                    models.DateField(
                        auto_now=True, verbose_name="Дата последнего изменения"
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=250,
                        verbose_name="Название",
                    ),
                ),
                (
                    "article",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=250,
                        verbose_name="Артикул",
                    ),
                ),
                (
                    "price",
                    models.PositiveIntegerField(
                        blank=True, default=0, verbose_name="Цена"
                    ),
                ),
            ],
            options={
                "verbose_name": "Мерч",
                "verbose_name_plural": "Мерч",
                "ordering": ("title",),
            },
        ),
    ]
