# Generated by Django 4.2.10 on 2024-02-26 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Merch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.TextField(verbose_name="Название")),
                ("article", models.TextField(verbose_name="Артикул")),
                ("price", models.IntegerField(verbose_name="Цена")),
            ],
            options={
                "verbose_name": "Мерч",
                "ordering": ("title",),
            },
        ),
    ]
