# Generated by Django 4.2.10 on 2024-03-03 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("merch", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="merch",
            name="article",
            field=models.CharField(
                blank=True, max_length=250, null=True, verbose_name="Артикул"
            ),
        ),
        migrations.AlterField(
            model_name="merch",
            name="title",
            field=models.CharField(
                blank=True,
                default="Без названия",
                max_length=250,
                verbose_name="Название",
            ),
        ),
    ]
