# Generated by Django 4.2.10 on 2024-03-03 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("merch", "0004_alter_merch_created_alter_merch_updated"),
    ]

    operations = [
        migrations.AlterField(
            model_name="merch",
            name="article",
            field=models.CharField(
                blank=True, default="", max_length=250, verbose_name="Артикул"
            ),
        ),
        migrations.AlterField(
            model_name="merch",
            name="price",
            field=models.PositiveIntegerField(
                blank=True, default=0, verbose_name="Цена"
            ),
        ),
        migrations.AlterField(
            model_name="merch",
            name="title",
            field=models.CharField(
                blank=True,
                default="Без названия",
                max_length=250,
                verbose_name="Название",
            ),
        ),
    ]
