# Generated by Django 4.2.10 on 2024-02-24 13:50

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AmbassadorGoal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        max_length=250, verbose_name="Цель амбассадорства"
                    ),
                ),
            ],
            options={
                "verbose_name": "Цель амбассадорства",
                "verbose_name_plural": "Цели амбассадорства",
            },
        ),
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        max_length=250, verbose_name="Название курса"
                    ),
                ),
            ],
            options={
                "verbose_name": "Курс Яндекс Практикума",
                "verbose_name_plural": "Курсы Яндекс Практикума",
            },
        ),
        migrations.CreateModel(
            name="EducationGoal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        max_length=250, verbose_name="Цель обучения в ЯП"
                    ),
                ),
            ],
            options={
                "verbose_name": "Цель обучения в ЯП",
                "verbose_name_plural": "Цели обучения в ЯП",
            },
        ),
        migrations.CreateModel(
            name="Promo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "value",
                    models.CharField(max_length=250, verbose_name="Промокод"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Активный"),
                            ("archive", "Архивный"),
                        ],
                        default="active",
                        max_length=50,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата регистрации"
                    ),
                ),
                (
                    "updated",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Дата последнего изменения"
                    ),
                ),
            ],
            options={
                "verbose_name": "Промокод",
                "verbose_name_plural": "Промокоды",
            },
        ),
        migrations.CreateModel(
            name="Ambassador",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="Уникальный идентификатор",
                    ),
                ),
                (
                    "telegram",
                    models.CharField(
                        max_length=250,
                        null=True,
                        verbose_name="Ник в телеграм",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=250, null=True, verbose_name="ФИО"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Активный"),
                            ("paused", "На паузе"),
                            ("not_ambassador", "Не амбассадор"),
                            ("pending", "Уточняется"),
                        ],
                        default="active",
                        max_length=50,
                        verbose_name="Статус амбассадора",
                    ),
                ),
                (
                    "onboarding_status",
                    models.BooleanField(
                        default=False, verbose_name="Статус онбординга"
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата регистрации"
                    ),
                ),
                (
                    "updated",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Дата последнего изменения"
                    ),
                ),
                (
                    "sex",
                    models.CharField(
                        choices=[
                            ("m", "Мужской"),
                            ("w", "Женский"),
                            ("Unknown", "Пол не указан"),
                        ],
                        default="Unknown",
                        max_length=50,
                        verbose_name="Пол амбассадора",
                    ),
                ),
                (
                    "country",
                    models.CharField(
                        max_length=250, null=True, verbose_name="Страна"
                    ),
                ),
                (
                    "city",
                    models.CharField(
                        max_length=250, null=True, verbose_name="Город"
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        max_length=250, null=True, verbose_name="Адрес"
                    ),
                ),
                (
                    "index",
                    models.CharField(
                        max_length=250, null=True, verbose_name="Индекс"
                    ),
                ),
                (
                    "email",
                    models.CharField(
                        max_length=250, null=True, verbose_name="Email"
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        max_length=250, null=True, verbose_name="Телефон"
                    ),
                ),
                (
                    "current_work",
                    models.CharField(
                        max_length=250, verbose_name="Текущее место работы"
                    ),
                ),
                (
                    "education",
                    models.CharField(
                        max_length=250, null=True, verbose_name="Образование"
                    ),
                ),
                (
                    "blog_link",
                    models.CharField(
                        max_length=250,
                        null=True,
                        verbose_name="Ссылка на свой блог",
                    ),
                ),
                (
                    "clothing_size",
                    models.CharField(
                        choices=[
                            ("xs", "XS - Экстра-маленький"),
                            ("s", "S - Маленький"),
                            ("m", "M - Средний"),
                            ("l", "L - Большой"),
                            ("xl", "XL - Очень большой"),
                            ("Unknown", "Размер не указан"),
                        ],
                        default="Unknown",
                        max_length=250,
                        verbose_name="Размер одежды",
                    ),
                ),
                (
                    "foot_size",
                    models.CharField(
                        max_length=250, verbose_name="Размер ноги"
                    ),
                ),
                (
                    "comment",
                    models.CharField(
                        max_length=250, verbose_name="Комментарий"
                    ),
                ),
                (
                    "ambassadors_goals",
                    models.ManyToManyField(
                        to="ambassadors.ambassadorgoal",
                        verbose_name="Цели амбассадорства",
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ambassadors",
                        to="ambassadors.course",
                        verbose_name="Пройденный курс ЯП",
                    ),
                ),
                (
                    "education_goal",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ambassadors",
                        to="ambassadors.educationgoal",
                        verbose_name="Цель обучения в ЯП",
                    ),
                ),
                (
                    "promo",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ambassador",
                        to="ambassadors.promo",
                        verbose_name="Промокод амбассадора",
                    ),
                ),
            ],
            options={
                "verbose_name": "Амбассадор",
                "verbose_name_plural": "Амбассадоры",
                "ordering": ("-created",),
            },
        ),
    ]
