# Generated by Django 4.2.10 on 2024-02-28 10:36

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("merch", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Ambassador",
            fields=[
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Дата последнего изменения"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="Уникальный идентификатор",
                    ),
                ),
                (
                    "telegram",
                    models.CharField(
                        blank=True,
                        max_length=250,
                        null=True,
                        verbose_name="Ник в телеграм",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        max_length=250,
                        null=True,
                        verbose_name="ФИО",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Активный"),
                            ("paused", "На паузе"),
                            ("not_ambassador", "Не амбассадор"),
                            ("pending", "Уточняется"),
                        ],
                        default="active",
                        max_length=50,
                        verbose_name="Статус амбассадора",
                    ),
                ),
                (
                    "onboarding_status",
                    models.BooleanField(
                        default=False, verbose_name="Статус онбординга"
                    ),
                ),
                (
                    "sex",
                    models.CharField(
                        choices=[
                            ("m", "Мужской"),
                            ("w", "Женский"),
                            ("Unknown", "Пол не указан"),
                        ],
                        default="Unknown",
                        max_length=50,
                        verbose_name="Пол амбассадора",
                    ),
                ),
                (
                    "country",
                    models.CharField(
                        blank=True,
                        max_length=250,
                        null=True,
                        verbose_name="Страна",
                    ),
                ),
                (
                    "city",
                    models.CharField(
                        blank=True,
                        max_length=250,
                        null=True,
                        verbose_name="Город",
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        blank=True,
                        max_length=250,
                        null=True,
                        verbose_name="Адрес",
                    ),
                ),
                (
                    "index",
                    models.CharField(
                        blank=True,
                        max_length=250,
                        null=True,
                        verbose_name="Индекс",
                    ),
                ),
                (
                    "email",
                    models.CharField(
                        blank=True,
                        max_length=250,
                        null=True,
                        verbose_name="Email",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True,
                        max_length=250,
                        null=True,
                        verbose_name="Телефон",
                    ),
                ),
                (
                    "current_work",
                    models.CharField(
                        blank=True,
                        max_length=250,
                        null=True,
                        verbose_name="Текущее место работы",
                    ),
                ),
                (
                    "education",
                    models.CharField(
                        blank=True,
                        max_length=250,
                        null=True,
                        verbose_name="Образование",
                    ),
                ),
                (
                    "blog_link",
                    models.CharField(
                        blank=True,
                        max_length=250,
                        null=True,
                        verbose_name="Ссылка на блог",
                    ),
                ),
                (
                    "clothing_size",
                    models.CharField(
                        choices=[
                            ("xs", "XS - Экстра-маленький"),
                            ("s", "S - Маленький"),
                            ("m", "M - Средний"),
                            ("l", "L - Большой"),
                            ("xl", "XL - Очень большой"),
                            ("Unknown", "Размер не указан"),
                        ],
                        default="Unknown",
                        max_length=250,
                        verbose_name="Размер одежды",
                    ),
                ),
                (
                    "foot_size",
                    models.CharField(
                        blank=True,
                        max_length=250,
                        null=True,
                        verbose_name="Размер ноги",
                    ),
                ),
                (
                    "comment",
                    models.CharField(
                        blank=True,
                        max_length=250,
                        null=True,
                        verbose_name="Комментарий",
                    ),
                ),
            ],
            options={
                "verbose_name": "Амбассадор",
                "verbose_name_plural": "Амбассадоры",
                "ordering": ("-created",),
            },
        ),
        migrations.CreateModel(
            name="AmbassadorGoal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Дата последнего изменения"
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        max_length=250, verbose_name="Цель амбассадорства"
                    ),
                ),
            ],
            options={
                "verbose_name": "Цель амбассадорства",
                "verbose_name_plural": "Цели амбассадорства",
            },
        ),
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Дата последнего изменения"
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        max_length=250, verbose_name="Название курса"
                    ),
                ),
            ],
            options={
                "verbose_name": "Курс Яндекс Практикума",
                "verbose_name_plural": "Курсы Яндекс Практикума",
            },
        ),
        migrations.CreateModel(
            name="EducationGoal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Дата последнего изменения"
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        max_length=250, verbose_name="Цель обучения в ЯП"
                    ),
                ),
            ],
            options={
                "verbose_name": "Цель обучения в ЯП",
                "verbose_name_plural": "Цели обучения в ЯП",
            },
        ),
        migrations.CreateModel(
            name="Promo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Дата последнего изменения"
                    ),
                ),
                (
                    "value",
                    models.CharField(max_length=250, verbose_name="Промокод"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Активный"),
                            ("archive", "Архивный"),
                        ],
                        default="active",
                        max_length=50,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "ambassador",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="promos",
                        to="ambassadors.ambassador",
                        verbose_name="Амбассадор",
                    ),
                ),
            ],
            options={
                "verbose_name": "Промокод",
                "verbose_name_plural": "Промокоды",
            },
        ),
        migrations.CreateModel(
            name="MerchMiddle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "size",
                    models.CharField(
                        choices=[
                            ("1", "XS"),
                            ("2", "S"),
                            ("3", "M"),
                            ("4", "L"),
                            ("5", "XL"),
                        ],
                        max_length=1,
                        verbose_name="Размер",
                    ),
                ),
                (
                    "delivery_cost",
                    models.IntegerField(
                        null=True, verbose_name="Стоимость доставки"
                    ),
                ),
                ("count", models.IntegerField(verbose_name="Количество")),
                (
                    "old_price",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Архивная цена"
                    ),
                ),
                (
                    "ambassador",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ambassador",
                        to="ambassadors.ambassador",
                        verbose_name="амбассадор",
                    ),
                ),
                (
                    "merch",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="merch.merch",
                        verbose_name="мерч",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="ambassador",
            name="ambassador_goals",
            field=models.ManyToManyField(
                related_name="ambassador",
                to="ambassadors.ambassadorgoal",
                verbose_name="Цели амбассадорства",
            ),
        ),
        migrations.AddField(
            model_name="ambassador",
            name="course",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="ambassadors",
                to="ambassadors.course",
                verbose_name="Пройденный курс ЯП",
            ),
        ),
        migrations.AddField(
            model_name="ambassador",
            name="education_goal",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="ambassadors",
                to="ambassadors.educationgoal",
                verbose_name="Цель обучения в ЯП",
            ),
        ),
        migrations.AddField(
            model_name="ambassador",
            name="merch",
            field=models.ManyToManyField(
                related_name="ambassador",
                through="ambassadors.MerchMiddle",
                to="merch.merch",
                verbose_name="Мерч",
            ),
        ),
    ]
