# Generated by Django 4.2.10 on 2024-02-28 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("ambassadors", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="merchmiddle",
            name="ambassador",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ambassador",
                to="ambassadors.ambassador",
                verbose_name="амбассадор",
            ),
            preserve_default=False,
        ),
    ]
