# Generated by Django 4.2.10 on 2024-03-03 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("merch", "0002_alter_merch_article_alter_merch_title"),
        ("ambassadors", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="merchmiddle",
            name="ambassador",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ambassador",
                to="ambassadors.ambassador",
                verbose_name="амбассадор",
            ),
        ),
        migrations.AlterField(
            model_name="merchmiddle",
            name="count",
            field=models.PositiveIntegerField(
                blank=True, default=1, verbose_name="Количество"
            ),
        ),
        migrations.AlterField(
            model_name="merchmiddle",
            name="merch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="merch",
                to="merch.merch",
                verbose_name="мерч",
            ),
        ),
    ]
