# Generated by Django 4.2.10 on 2024-02-24 21:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "ambassadors",
            "0002_ambassadorgoal_created_ambassadorgoal_updated_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="ambassador",
            name="address",
            field=models.CharField(
                blank=True, max_length=250, null=True, verbose_name="Адрес"
            ),
        ),
        migrations.AlterField(
            model_name="ambassador",
            name="blog_link",
            field=models.CharField(
                blank=True,
                max_length=250,
                null=True,
                verbose_name="Ссылка на блог",
            ),
        ),
        migrations.AlterField(
            model_name="ambassador",
            name="city",
            field=models.CharField(
                blank=True, max_length=250, null=True, verbose_name="Город"
            ),
        ),
        migrations.AlterField(
            model_name="ambassador",
            name="comment",
            field=models.CharField(
                blank=True,
                max_length=250,
                null=True,
                verbose_name="Комментарий",
            ),
        ),
        migrations.AlterField(
            model_name="ambassador",
            name="country",
            field=models.CharField(
                blank=True, max_length=250, null=True, verbose_name="Страна"
            ),
        ),
        migrations.AlterField(
            model_name="ambassador",
            name="course",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="ambassadors",
                to="ambassadors.course",
                verbose_name="Пройденный курс ЯП",
            ),
        ),
        migrations.AlterField(
            model_name="ambassador",
            name="education",
            field=models.CharField(
                blank=True,
                max_length=250,
                null=True,
                verbose_name="Образование",
            ),
        ),
        migrations.AlterField(
            model_name="ambassador",
            name="education_goal",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="ambassadors",
                to="ambassadors.educationgoal",
                verbose_name="Цель обучения в ЯП",
            ),
        ),
        migrations.AlterField(
            model_name="ambassador",
            name="email",
            field=models.CharField(
                blank=True, max_length=250, null=True, verbose_name="Email"
            ),
        ),
        migrations.AlterField(
            model_name="ambassador",
            name="foot_size",
            field=models.CharField(
                blank=True,
                max_length=250,
                null=True,
                verbose_name="Размер ноги",
            ),
        ),
        migrations.AlterField(
            model_name="ambassador",
            name="index",
            field=models.CharField(
                blank=True, max_length=250, null=True, verbose_name="Индекс"
            ),
        ),
        migrations.AlterField(
            model_name="ambassador",
            name="name",
            field=models.CharField(
                blank=True, max_length=250, null=True, verbose_name="ФИО"
            ),
        ),
        migrations.AlterField(
            model_name="ambassador",
            name="phone",
            field=models.CharField(
                blank=True, max_length=250, null=True, verbose_name="Телефон"
            ),
        ),
        migrations.AlterField(
            model_name="ambassador",
            name="promo",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="ambassador",
                to="ambassadors.promo",
                verbose_name="Промокод амбассадора",
            ),
        ),
        migrations.AlterField(
            model_name="ambassador",
            name="telegram",
            field=models.CharField(
                blank=True,
                max_length=250,
                null=True,
                verbose_name="Ник в телеграм",
            ),
        ),
    ]
