# Generated by Django 4.2.10 on 2024-02-24 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "ambassadors",
            "0003_alter_ambassador_address_alter_ambassador_blog_link_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="ambassador",
            name="current_work",
            field=models.CharField(
                blank=True,
                max_length=250,
                null=True,
                verbose_name="Текущее место работы",
            ),
        ),
    ]
