# Generated by Django 4.2.10 on 2024-02-25 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("ambassadors", "0004_alter_ambassador_current_work"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ambassador",
            name="promo",
        ),
        migrations.AddField(
            model_name="promo",
            name="ambassador",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="promos",
                to="ambassadors.ambassador",
                verbose_name="Амбассадор",
            ),
        ),
    ]
