# Generated by Django 4.2.10 on 2024-02-25 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ambassadors", "0005_remove_ambassador_promo_promo_ambassador"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ambassador",
            name="ambassadors_goals",
        ),
        migrations.AddField(
            model_name="ambassador",
            name="ambassador_goals",
            field=models.ManyToManyField(
                related_name="ambassador",
                to="ambassadors.ambassadorgoal",
                verbose_name="Цели амбассадорства",
            ),
        ),
    ]
