# Generated by Django 4.2.10 on 2024-02-26 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "merch",
            "0002_merch_created_merch_updated_alter_merch_article_and_more",
        ),
        ("ambassadors", "0006_remove_ambassador_ambassadors_goals_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="MerchMiddle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Дата последнего изменения"
                    ),
                ),
                (
                    "size",
                    models.CharField(
                        choices=[
                            ("xs", "XS - Экстра-маленький"),
                            ("s", "S - Маленький"),
                            ("m", "M - Средний"),
                            ("l", "L - Большой"),
                            ("xl", "XL - Очень большой"),
                            ("Unknown", "Размер не указан"),
                        ],
                        max_length=250,
                        verbose_name="Размер",
                    ),
                ),
                (
                    "delivery_cost",
                    models.IntegerField(
                        null=True, verbose_name="Стоимость доставки"
                    ),
                ),
                ("count", models.IntegerField(verbose_name="Количество")),
                (
                    "old_price",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Архивная цена"
                    ),
                ),
                (
                    "ambassador",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ambassadors.ambassador",
                        verbose_name="амбассадор",
                    ),
                ),
                (
                    "merch",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="merch.merch",
                        verbose_name="мерч",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="ambassador",
            name="merch",
            field=models.ManyToManyField(
                related_name="ambassador",
                through="ambassadors.MerchMiddle",
                to="merch.merch",
                verbose_name="Мерч",
            ),
        ),
    ]
