# Generated by Django 4.2.10 on 2024-02-25 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ambassadors", "0006_remove_ambassador_ambassadors_goals_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ambassador",
            name="created",
            field=models.DateField(
                auto_now_add=True, verbose_name="Дата создания"
            ),
        ),
        migrations.AlterField(
            model_name="ambassador",
            name="updated",
            field=models.DateField(
                auto_now=True, verbose_name="Дата последнего изменения"
            ),
        ),
        migrations.AlterField(
            model_name="ambassadorgoal",
            name="created",
            field=models.DateField(
                auto_now_add=True, verbose_name="Дата создания"
            ),
        ),
        migrations.AlterField(
            model_name="ambassadorgoal",
            name="updated",
            field=models.DateField(
                auto_now=True, verbose_name="Дата последнего изменения"
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="created",
            field=models.DateField(
                auto_now_add=True, verbose_name="Дата создания"
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="updated",
            field=models.DateField(
                auto_now=True, verbose_name="Дата последнего изменения"
            ),
        ),
        migrations.AlterField(
            model_name="educationgoal",
            name="created",
            field=models.DateField(
                auto_now_add=True, verbose_name="Дата создания"
            ),
        ),
        migrations.AlterField(
            model_name="educationgoal",
            name="updated",
            field=models.DateField(
                auto_now=True, verbose_name="Дата последнего изменения"
            ),
        ),
        migrations.AlterField(
            model_name="promo",
            name="created",
            field=models.DateField(
                auto_now_add=True, verbose_name="Дата создания"
            ),
        ),
        migrations.AlterField(
            model_name="promo",
            name="updated",
            field=models.DateField(
                auto_now=True, verbose_name="Дата последнего изменения"
            ),
        ),
    ]
