# Generated by Django 4.2.10 on 2024-02-26 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0001_initial"),
        ("ambassadors", "0006_remove_ambassador_ambassadors_goals_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="ambassador",
            name="content",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="ambassador",
                to="content.content",
                verbose_name="Контент амбассадора",
            ),
        ),
    ]
