# Generated by Django 4.2.10 on 2024-02-26 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("merch", "0003_alter_merch_options_alter_merch_price"),
        ("ambassadors", "0007_merchmiddle_ambassador_merch"),
    ]

    operations = [
        migrations.AlterField(
            model_name="merchmiddle",
            name="ambassador",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="ambassadors.ambassador",
                verbose_name="амбассадор",
            ),
        ),
        migrations.AlterField(
            model_name="merchmiddle",
            name="count",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Количество"
            ),
        ),
        migrations.AlterField(
            model_name="merchmiddle",
            name="delivery_cost",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Стоимость доставки"
            ),
        ),
        migrations.AlterField(
            model_name="merchmiddle",
            name="merch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="merch.merch",
                verbose_name="мерч",
            ),
        ),
        migrations.AlterField(
            model_name="merchmiddle",
            name="old_price",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Архивная цена"
            ),
        ),
    ]
