# Generated by Django 4.2.10 on 2024-02-26 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "ambassadors",
            "0008_alter_merchmiddle_ambassador_alter_merchmiddle_count_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="merchmiddle",
            options={
                "verbose_name": "Мерч амбассадора",
                "verbose_name_plural": "Мерч амбассадора",
            },
        ),
    ]
