# Generated by Django 4.2.10 on 2024-02-26 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ambassadors", "0009_alter_merchmiddle_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ambassador",
            name="ambassador_goals",
            field=models.ManyToManyField(
                blank=True,
                related_name="ambassador",
                to="ambassadors.ambassadorgoal",
                verbose_name="Цели амбассадорства",
            ),
        ),
    ]
