# Generated by Django 4.2.10 on 2024-02-26 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "ambassadors",
            "0007_alter_ambassador_created_alter_ambassador_updated_and_more",
        ),
        ("ambassadors", "0010_alter_ambassador_ambassador_goals"),
    ]

    operations = []
