# Generated by Django 4.2.10 on 2024-02-26 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ambassadors", "0011_merge_20240226_2054"),
    ]

    operations = [
        migrations.AlterField(
            model_name="merchmiddle",
            name="created",
            field=models.DateField(
                auto_now_add=True, verbose_name="Дата создания"
            ),
        ),
        migrations.AlterField(
            model_name="merchmiddle",
            name="updated",
            field=models.DateField(
                auto_now=True, verbose_name="Дата последнего изменения"
            ),
        ),
        migrations.AlterField(
            model_name="promo",
            name="status",
            field=models.CharField(
                choices=[("active", "Активный"), ("archived", "Архивный")],
                default="active",
                max_length=50,
                verbose_name="Статус",
            ),
        ),
    ]
