# Generated by Django 4.2.10 on 2024-02-27 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "ambassadors",
            "0012_alter_merchmiddle_created_alter_merchmiddle_updated_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="merchmiddle",
            name="size",
            field=models.CharField(
                blank=True,
                choices=[
                    ("xs", "XS - Экстра-маленький"),
                    ("s", "S - Маленький"),
                    ("m", "M - Средний"),
                    ("l", "L - Большой"),
                    ("xl", "XL - Очень большой"),
                    ("Unknown", "Размер не указан"),
                ],
                max_length=250,
                null=True,
                verbose_name="Размер",
            ),
        ),
    ]
