# Generated by Django 4.2.10 on 2024-03-03 20:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("merch", "0005_alter_merch_article_alter_merch_price_and_more"),
        ("ambassadors", "0015_alter_ambassador_clothing_size_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="merchmiddle",
            options={
                "ordering": ("-created",),
                "verbose_name": "Мерч амбассадора",
                "verbose_name_plural": "Мерч амбассадора",
            },
        ),
        migrations.AlterField(
            model_name="merchmiddle",
            name="ambassador",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sent_merch",
                to="ambassadors.ambassador",
                verbose_name="амбассадор",
            ),
        ),
        migrations.AlterField(
            model_name="merchmiddle",
            name="count",
            field=models.PositiveIntegerField(
                blank=True, default=1, verbose_name="Количество"
            ),
        ),
        migrations.AlterField(
            model_name="merchmiddle",
            name="delivery_cost",
            field=models.PositiveIntegerField(
                blank=True, default=0, verbose_name="Стоимость доставки"
            ),
        ),
        migrations.AlterField(
            model_name="merchmiddle",
            name="merch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sent",
                to="merch.merch",
                verbose_name="мерч",
            ),
        ),
        migrations.AlterField(
            model_name="merchmiddle",
            name="old_price",
            field=models.PositiveIntegerField(
                blank=True, default=0, verbose_name="Архивная цена"
            ),
        ),
        migrations.AlterField(
            model_name="merchmiddle",
            name="size",
            field=models.CharField(
                blank=True,
                choices=[
                    ("XS", "XS - Экстра-маленький"),
                    ("S", "S - Маленький"),
                    ("M", "M - Средний"),
                    ("L", "L - Большой"),
                    ("XL", "XL - Очень большой"),
                    ("UNKNOWN", "Размер не указан"),
                ],
                default="UNKNOWN",
                max_length=250,
                verbose_name="Размер",
            ),
        ),
    ]
