# Generated by Django 4.2.10 on 2024-03-06 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ambassadors", "0016_alter_merchmiddle_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="merchmiddle",
            name="size",
            field=models.CharField(
                blank=True,
                choices=[
                    ("XS", "XS - Экстра-маленький"),
                    ("S", "S - Маленький"),
                    ("M", "M - Средний"),
                    ("L", "L - Большой"),
                    ("XL", "XL - Очень большой"),
                    ("UNKNOWN", "Размер не указан"),
                ],
                default="UNKNOWN",
                max_length=250,
                null=True,
                verbose_name="Размер",
            ),
        ),
    ]
