# Generated by Django 4.2.10 on 2024-03-09 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ambassadors", "0017_alter_merchmiddle_size"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ambassador",
            name="clothing_size",
            field=models.CharField(
                choices=[
                    ("XS", "XS"),
                    ("S", "S"),
                    ("M", "M"),
                    ("L", "L"),
                    ("XL", "XL"),
                    ("UNKNOWN", "Размер не указан"),
                ],
                default="UNKNOWN",
                max_length=250,
                verbose_name="Размер одежды",
            ),
        ),
        migrations.AlterField(
            model_name="merchmiddle",
            name="size",
            field=models.CharField(
                blank=True,
                choices=[
                    ("XS", "XS"),
                    ("S", "S"),
                    ("M", "M"),
                    ("L", "L"),
                    ("XL", "XL"),
                    ("UNKNOWN", "Размер не указан"),
                ],
                default="UNKNOWN",
                max_length=250,
                null=True,
                verbose_name="Размер",
            ),
        ),
    ]
