# Generated by Django 4.2.10 on 2024-02-28 12:13

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("ambassadors", "__first__"),
    ]

    operations = [
        migrations.CreateModel(
            name="Content",
            fields=[
                (
                    "created",
                    models.DateField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated",
                    models.DateField(
                        auto_now=True, verbose_name="Дата последнего изменения"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="Уникальный идентификатор",
                    ),
                ),
                (
                    "platform",
                    models.CharField(
                        blank=True,
                        max_length=250,
                        null=True,
                        verbose_name="Площадка размещения контента",
                    ),
                ),
                (
                    "link",
                    models.CharField(
                        blank=True,
                        max_length=250,
                        null=True,
                        verbose_name="Ссылка на контент",
                    ),
                ),
                (
                    "file",
                    models.CharField(
                        blank=True,
                        max_length=250,
                        null=True,
                        verbose_name="Ссылка на файл",
                    ),
                ),
                (
                    "guide",
                    models.BooleanField(
                        default=False, verbose_name="Контент в рамках гайда"
                    ),
                ),
                (
                    "ambassador",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="content",
                        to="ambassadors.ambassador",
                        verbose_name="Амбассадор",
                    ),
                ),
            ],
            options={
                "verbose_name": "Контент",
                "verbose_name_plural": "Контент",
                "ordering": ("-created",),
            },
        ),
    ]
