# Generated by Django 4.2.10 on 2024-02-26 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("ambassadors", "0010_alter_ambassador_ambassador_goals"),
        ("content", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="content",
            name="ambassador",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="content",
                to="ambassadors.ambassador",
                verbose_name="Амбассадор",
            ),
        ),
    ]
