# Generated by Django 4.2.10 on 2024-02-26 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0002_content_ambassador"),
    ]

    operations = [
        migrations.AlterField(
            model_name="content",
            name="created",
            field=models.DateField(
                auto_now_add=True, verbose_name="Дата создания"
            ),
        ),
        migrations.AlterField(
            model_name="content",
            name="updated",
            field=models.DateField(
                auto_now=True, verbose_name="Дата последнего изменения"
            ),
        ),
    ]
