# Generated by Django 4.2.10 on 2024-03-05 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0004_content_yandex_form_alter_content_created_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="content",
            name="platform",
        ),
    ]
