# Generated by Django 4.2.10 on 2024-03-07 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0005_remove_content_platform"),
    ]

    operations = [
        migrations.AlterField(
            model_name="content",
            name="guide",
            field=models.CharField(
                default=False,
                max_length=4,
                verbose_name="Контент в рамках гайда",
            ),
        ),
    ]
